name: creditop_account_deletion_web
description: Creditop Account Deletion Web - Cumplimiento Play Store y App Store
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0

  # Navigation
  go_router: ^16.3.0

  # Network
  dio: ^5.9.0

  # Auth
  amplify_flutter: ^2.7.0
  amplify_auth_cognito: ^2.7.0

  # Environment
  flutter_dotenv: ^5.2.1

  # Local packages
  core:
    path: ../packages/core
  cds_web:
    path: ../packages/cds_web
  feature_auth:
    path: ../packages/feature_auth
  feature_delete_account:
    path: ../packages/feature_delete_account

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^3.0.0
  custom_lint:
  riverpod_lint:
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.dev

